[project]
name        = 'rx_classifier'
version     = '0.0.2'
dependencies= [
'data_manipulation_utilities', 
'mplhep', 
'matplotlib',
'numpy',
'joblib',
'PyYAML',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
train_classifier='rx_classifier_scripts.train_classifier:main'
apply_classifier='rx_classifier_scripts.apply_classifier:main'

[tool.setuptools.package-data]
rx_classifier_data=['rx_classifier_data/*.yaml']

[tool.setuptools]
