q2:
  low    : (Jpsi_M * Jpsi_M >        0) && (Jpsi_M * Jpsi_M <  1100000)
  central: (Jpsi_M * Jpsi_M >  1100000) && (Jpsi_M * Jpsi_M <  6000000)
  jpsi   : (Jpsi_M * Jpsi_M >  6000000) && (Jpsi_M * Jpsi_M < 12960000)
  psi2   : (Jpsi_M * Jpsi_M >  9920000) && (Jpsi_M * Jpsi_M < 16400000)
  high   : (Jpsi_M * Jpsi_M > 15500000) && (Jpsi_M * Jpsi_M < 22000000)
hyper               :
  loss              : log_loss
  max_depth         : 3
  min_samples_split : 2
# ----------------------------------
dataset :
  selection:
    bkg :
      mass : mass > 0
    sig :
      mass : 'mass > 4500 && mass < 5600'
  paths:
    sig :
      file_path : 
        - /publicfs/ucas/user/campoverde/Data/RX_run3/v3/NO_q2_bdt_mass_Q2_central_VR_v1/Bu_Kee_eq_btosllball05_DPC/Hlt2RD_BuToKpEE_MVA/*.root
      tree_name : DecayTree 
    bkg :
      file_path : 
        - /publicfs/ucas/user/campoverde/Data/RX_run3/v3/NO_q2_bdt_mass_Q2_central_VR_v1/Bd_Kstee_eq_btosllball05_DPC/Hlt2RD_BuToKpEE_MVA/*.root
        - /publicfs/ucas/user/campoverde/Data/RX_run3/v3/NO_q2_bdt_mass_Q2_central_VR_v1/Bu_Kstee_Kpi0_eq_btosllball05_DPC/Hlt2RD_BuToKpEE_MVA/*.root
      tree_name : DecayTree 
  define :
    mass        : B_M
    log_b_pt    : TMath::Log(B_PT)
    sqrt_ipchi2 : TMath::Sqrt(B_IPCHI2_OWNPV) 
    acos_dira   : TMath::ACos(B_DIRA_OWNPV)
    iso_mult    : B_HEAD_CC_B_ChargedIso_DR2_0p20_CMULT
    iso_mom     : B_HEAD_CC_B_ChargedIso_DR2_0p20_CP
    sqrt_jipchi2: TMath::Sqrt(Jpsi_IPCHI2_OWNPV) 
    jp_acos_dira: TMath::ACos(Jpsi_DIRA_OWNPV)
    log_h_pt    : TMath::Log(H_PT)
    min_ll_ipc  : TMath::Min(TMath::Sqrt(L1_IPCHI2_OWNPV), TMath::Sqrt(L2_IPCHI2_OWNPV))
training :
  nfold    : 10
  rdm_stat : 1
  hyper:
    low : 
      n_estimators : 20
      learning_rate: 0.02
      max_depth    : 2
    central : 
      n_estimators : 70
      learning_rate: 0.05
    high : 
      n_estimators : 50
      learning_rate: 0.05
  features : 
    - log_b_pt
    - sqrt_ipchi2
    - acos_dira
    - iso_mult
    - iso_mom
    - sqrt_jipchi2
    - jp_acos_dira
    - log_h_pt
    - min_ll_ipc
saving:
  path : 'output/mva_rare_2024_prc/VERSION/model.pkl'
plotting:
  roc :
    min : [0.1, 0.1]
  val_dir : 'output/mva_rare_2024_prc/VERSION/plots'
  features:
    saving:
      plt_dir : 'output/mva_rare_2024_prc/VERSION/plots/features'
    plots:
      log_b_pt  :
        normalized : true
        binning : [6, 11, 40]
        yscale  : 'linear'
        labels  : ['$\log(p_T)(B^+)$', '']
      sqrt_ipchi2:
        normalized : true
        yscale  : 'linear'
        binning : [0, 6, 40]
        labels  : ['$\sqrt{IP_{\chi^2}}(B^+)$', '']
      acos_dira:
        normalized : true
        binning : [0, 0.03, 40]
        yscale  : 'log'
        labels  : ['$\arccos(DIRA)(B^+)$', '']
      iso_mult:
        normalized : true
        binning : [0, 15, 15]
        yscale  : 'linear'
        labels  : ['Iso$_{mult}(B^+)$', '']
      iso_mom:
        normalized : true
        yscale  : 'linear'
        binning : [0, 200000, 40]
        labels  : ['Iso$(p)(B^+)$MeV', '']
      sqrt_jipchi2:
        normalized : true
        binning : [0, 100, 40]
        yscale  : 'linear'
        labels  : ['$\sqrt{IP_{\chi^2}}(J/\psi)$', '']
      jp_acos_dira:
        normalized : true
        binning : [0, 0.2, 40]
        yscale  : 'log'
        labels  : ['$\arccos(DIRA)(J/\psi^+)$', '']
      log_h_pt  :
        normalized : true
        binning : [6, 11, 40]
        yscale  : 'linear'
        labels  : ['$\log(p_T)(K^+)$', '']
      min_ll_ipc:
        normalized : true
        binning : [0, 60, 40]
        yscale  : 'linear'
        labels  : ['$\min(IP_{\chi^2}(e^+), IP_{\chi^2}(e^-))$', '']
      mass:
        normalized : true
        binning : [4000, 6000, 50]
        yscale  : 'linear'
        labels  : ['$M(B^+)$', '']
