q2:
  low    : (Jpsi_M * Jpsi_M >        0) && (Jpsi_M * Jpsi_M <  1100000) && (hop_mass > 4500)
  central: (Jpsi_M * Jpsi_M >  1100000) && (Jpsi_M * Jpsi_M <  6000000) && (hop_mass > 4500)
  jpsi   : (Jpsi_M * Jpsi_M >  6000000) && (Jpsi_M * Jpsi_M < 12960000) && (hop_mass > 4500)
  psi2   : (Jpsi_M * Jpsi_M >  9920000) && (Jpsi_M * Jpsi_M < 16400000) && (hop_mass > 4500)
  high   : (Jpsi_M * Jpsi_M > 15500000) && (Jpsi_M * Jpsi_M < 22000000) && (hop_mass > 3000)
features:
  low:
    - log_b_pt
    - sqrt_ipchi2
    - sqrt_jipchi2
    - acos_dira
    - log_h_pt
    - min_ll_ipc
    - iso_one_mass 
    - iso_one_dchi
    - iso_cc_mom
    - iso_cc_ptasy
    - iso_nc_mom
    - iso_nc_ptasy
  central:
    - log_b_pt
    - sqrt_ipchi2
    - sqrt_jipchi2
    - acos_dira
    - log_h_pt
    - min_ll_ipc
    - iso_one_mass 
    - iso_one_dchi
    - iso_cc_mom
    - iso_cc_ptasy
    - iso_nc_mom
    - iso_nc_ptasy
  high:
    - log_b_pt
    - sqrt_ipchi2
    - sqrt_jipchi2
    - acos_dira
    - log_h_pt
    - min_ll_ipc
    - iso_one_mass 
    - iso_one_dchi
    - iso_cc_mom
    - iso_cc_ptasy
    - iso_nc_mom
    - iso_nc_ptasy
# ----------------------------------
hyper               :
  loss              : log_loss
  learning_rate     : 0.10
  max_depth         : 3
  min_samples_split : 2
# ----------------------------------
dataset :
  columns:
    - B_M
    - Jpsi_M
    - swp_cascade_mass_swp
    - swp_jpsi_misid_mass_swp
    - hop_mass
    - mva_cmb
    - B_PT
    - B_IPCHI2_OWNPV
    - B_HEAD_CC_B_ChargedIso_DR2_0p15_CP
    - B_HEAD_CC_B_ChargedIso_DR2_0p15_PTASY
    - B_HEAD_NC_B_NeutralIso_DR2_0p15_CP
    - B_HEAD_NC_B_NeutralIso_DR2_0p15_PTASY
    - B_VTXISO_B_OneTrack_DChi2Vtx_9p0_Smallest_DELTACHI2_MASS
    - B_VTXISO_B_OneTrack_DChi2Vtx_9p0_Smallest_DELTACHI2
    - Jpsi_IPCHI2_OWNPV 
    - B_DIRA_OWNPV
    - H_PT
    - L1_IPCHI2_OWNPV
    - L2_IPCHI2_OWNPV
  selection:
    bkg :
      casc : swp_cascade_mass_swp    < 1800 || swp_cascade_mass_swp    > 1900
      jmis : swp_jpsi_misid_mass_swp < 3050 || swp_jpsi_misid_mass_swp > 3150 
      tail : B_M < 5100
      mva  : mva_cmb > 0.7
    sig :
      casc : swp_cascade_mass_swp    < 1800 || swp_cascade_mass_swp    > 1900
      jmis : swp_jpsi_misid_mass_swp < 3050 || swp_jpsi_misid_mass_swp > 3150 
      mva  : mva_cmb > 0.7
  paths:
    mva  : /home/acampove/external_ssd/Data/samples/mva_v1.yaml # Use first version of MVA to clean for combinatorial, to train second version of PRC MVA
    hop  : /home/acampove/external_ssd/Data/samples/hop.yaml
    jmis : /home/acampove/external_ssd/Data/samples/jpsi_misid.yaml
    casc : /home/acampove/external_ssd/Data/samples/cascade.yaml
    main : /home/acampove/external_ssd/Data/samples/main.yaml 
  samples:
    sig :
      sample : Bu_Kee_eq_btosllball05_DPC
      trigger: Hlt2RD_BuToKpEE_MVA
    bkg :
      sample : DATA* 
      trigger: Hlt2RD_BuToKpMuMu_MVA
  define :
    mass        : B_M
    log_b_pt    : TMath::Log(B_PT)
    sqrt_ipchi2 : TMath::Sqrt(B_IPCHI2_OWNPV) 
    acos_dira   : TMath::ACos(B_DIRA_OWNPV)
    # ----------
    iso_cc_mom  : B_HEAD_CC_B_ChargedIso_DR2_0p15_CP
    iso_cc_ptasy: B_HEAD_CC_B_ChargedIso_DR2_0p15_PTASY

    iso_nc_mom  : B_HEAD_NC_B_NeutralIso_DR2_0p15_CP
    iso_nc_ptasy: B_HEAD_NC_B_NeutralIso_DR2_0p15_PTASY

    iso_one_mass: B_VTXISO_B_OneTrack_DChi2Vtx_9p0_Smallest_DELTACHI2_MASS
    iso_one_dchi: B_VTXISO_B_OneTrack_DChi2Vtx_9p0_Smallest_DELTACHI2
    # ----------
    sqrt_jipchi2: TMath::Sqrt(Jpsi_IPCHI2_OWNPV) 
    log_h_pt    : TMath::Log(H_PT)
    min_ll_ipc  : TMath::Min(TMath::Sqrt(L1_IPCHI2_OWNPV), TMath::Sqrt(L2_IPCHI2_OWNPV))
  nan :
    iso_one_mass :  3000
    iso_one_dchi : -1
    iso_cc_mom   : -10000
    iso_nc_mom   : -10000
training :
  nfold    : 10
  rdm_stat : 1
  hyper:
    low : 
      n_estimators : 70
    central : 
      n_estimators : 70
      max_depth    : 4
    high : 
      n_estimators : 70
saving:
  path : 'output/mva_rare_2024_prc/VERSION/model.pkl'
plotting:
  roc :
    min : [0.0, 0.0]
    annotate:
      sig_eff : [0.40, 0.5, 0.6, 0.7, 0.8, 0.9]
      form : '{:.2f}'
      color: 'green'
      xoff : -30
      yoff : -30
      size :  30
  correlation:
    size       : [20, 15]
    mask_value : 0
  val_dir : 'output/mva_rare_2024_prc/VERSION/plots'
  features:
    saving:
      plt_dir : 'output/mva_rare_2024_prc/VERSION/plots/features'
    plots:
      iso_cc_mom:
        normalized : true
        yscale  : 'linear'
        binning : [-20000, 200000, 40]
        labels  : ['Iso$_{CC}^P(B^+)$MeV', '']
      iso_cc_ptasy:
        normalized : true
        yscale  : 'linear'
        binning : [-1, +1, 40]
        labels  : ['Iso$_{CC}^{p_T, Asym}(B^+)$MeV', '']
      # --------------------
      iso_nc_mom:
        normalized : true
        yscale  : 'linear'
        binning : [-20000, 100000, 40]
        labels  : ['Iso$_{NC}^P(B^+)$MeV', '']
      iso_nc_ptasy:
        normalized : true
        yscale  : 'linear'
        binning : [-1, +1, 40]
        labels  : ['Iso$_{NC}^{p_T, Asym}(B^+)$MeV', '']
      # --------------------
      iso_one_mass:
        normalized : true
        binning : [2000, 8000, 40]
        yscale  : 'linear'
        labels  : ['Iso$_{mass}^{1Trk}(B^+)$', '']
      # --------------------
      iso_one_dchi:
        normalized : true
        binning : [-3, 15, 40]
        yscale  : 'linear'
        labels  : ['Iso$_{\Delta\chi^2}^{1Trk}(B^+)$', '']
      # --------------------
      log_b_pt  :
        normalized : true
        binning : [6, 11, 40]
        yscale  : 'linear'
        labels  : ['$\log(p_T)(B^+)$', '']
      sqrt_ipchi2:
        normalized : true
        yscale  : 'linear'
        binning : [0, 6, 40]
        labels  : ['$\sqrt{IP_{\chi^2}}(B^+)$', '']
      sqrt_jipchi2:
        normalized : true
        binning : [0, 100, 40]
        yscale  : 'linear'
        labels  : ['$\sqrt{IP_{\chi^2}}(J/\psi)$', '']
      acos_dira:
        normalized : true
        binning : [0, 0.03, 40]
        yscale  : 'log'
        labels  : ['$\arccos(DIRA)(B^+)$', '']
      log_h_pt  :
        normalized : true
        binning : [1, 10, 40]
        yscale  : 'linear'
        labels  : ['$\log(p_T)(K^+)$', '']
      min_ll_ipc:
        normalized : true
        binning : [0, 60, 40]
        yscale  : 'linear'
        labels  : ['$\min(IP_{\chi^2}(e^+), IP_{\chi^2}(e^-))$', '']
      # ---------------------
      mass:
        normalized : true
        binning : [3000, 6000, 100]
        yscale  : 'linear'
        labels  : ['$M(B^+)$', '']
      hop_mass:
        normalized : true
        binning : [1000, 7000, 60]
        yscale  : 'linear'
        labels  : ['$M_{HOP}(B^+)$', '']
      swp_cascade_mass_swp:
        normalized : true
        binning : [1700, 2200, 60]
        yscale  : 'linear'
        labels  : ['$M(K,\ell_{\to\pi})$', '']
      swp_jpsi_misid_mass_swp:
        normalized : true
        binning : [2800, 3400, 60]
        yscale  : 'linear'
        labels  : ['$M(K_{\to\ell},\ell)$', '']
