features:
  low:
    - B_PT
    - B_IPCHI2_OWNPV
    - B_FDCHI2_OWNPV
    - B_ENDVERTEX_CHI2DOF 
    - B_DIRA_OWNPV
    #
    - Jpsi_DIRA_OWNPV
    - Jpsi_CHI2DOF
    - Jpsi_IPCHI2_OWNPV
    #
    - max_ll_ipc
    - min_ll_ipc
    #
    - H_PT 
    - H_IPCHI2_OWNPV 
  central:
    - B_PT
    - B_IPCHI2_OWNPV
    - B_FDCHI2_OWNPV
    - B_ENDVERTEX_CHI2DOF 
    - B_DIRA_OWNPV
    #
    - Jpsi_PT
    - Jpsi_DIRA_OWNPV
    - Jpsi_CHI2DOF
    - Jpsi_IPCHI2_OWNPV
    #
    - min_ll_pt
    - max_ll_pt
    - max_ll_ipc
    - min_ll_ipc
    #
    - H_PT 
    - H_IPCHI2_OWNPV 
  high:
    - B_PT
    - B_IPCHI2_OWNPV
    - B_ENDVERTEX_CHI2DOF 
    - B_DIRA_OWNPV
    #
    - Jpsi_PT
    - Jpsi_DIRA_OWNPV
    - Jpsi_CHI2DOF
    - Jpsi_IPCHI2_OWNPV
    #
    - min_ll_pt
    - max_ll_ipc
    - min_ll_ipc
    #
    - H_PT 
    - H_IPCHI2_OWNPV 
# ----------------------------------
hyper               :
  loss              : log_loss
  learning_rate     : 0.10
  max_depth         : 3
  min_samples_split : 2
# ----------------------------------
dataset :
  selection:
    bkg :
      bdt  : (1)
      mass : mass > 5500
    sig :
      bdt  : (1)
      mass : (1) 
  paths:
    main : /home/acampove/external_ssd/Data/samples/main.yaml
    hop  : /home/acampove/external_ssd/Data/samples/hop.yaml
    jmis : /home/acampove/external_ssd/Data/samples/jpsi_misid.yaml
    casc : /home/acampove/external_ssd/Data/samples/cascade.yaml
  samples:
    sig :
      sample : Bu_Kee_eq_btosllball05_DPC # can be a list
      trigger: Hlt2RD_BuToKpEE_MVA
    bkg :
      sample : DATA*
      trigger: Hlt2RD_BuToKpEE_MVA
  define :
    mass       : 'B_M'
    min_ll_pt  : 'TMath::Min(L1_PT , L2_PT)'
    max_ll_pt  : 'TMath::Max(L1_PT , L2_PT)'
    min_ll_ipc : 'TMath::Min(L1_IPCHI2_OWNPV, L2_IPCHI2_OWNPV)'
    max_ll_ipc : 'TMath::Max(L1_IPCHI2_OWNPV, L2_IPCHI2_OWNPV)'
training :
  nfold    : 10
  rdm_stat : 1
  hyper:
    low : 
      n_estimators : 70
    central : 
      n_estimators : 70
      max_depth    : 4
    high : 
      n_estimators : 70
saving:
  path : 'output/mva_rare_2024_cmb/VERSION/model.pkl'
plotting:
  roc :
    min : [0.5, 0.9]
    annotate:
      sig_eff : [0.40, 0.5, 0.6, 0.7, 0.8, 0.9]
      form : '{:.2f}'
      color: 'green'
      xoff : -30
      yoff : -30
      size :  30
  correlation:
    size       : [20, 15]
    mask_value : 0
  val_dir : 'output/mva_rare_2024_cmb/VERSION/plots'
  features:
    saving:
      plt_dir : 'output/mva_rare_2024_cmb/VERSION/plots/features'
    plots:
      B_PT :
        normalized : true
        binning : [0, 30000, 100]
        yscale  : 'log'
        labels  : ['$p_T(B^+)$', '']
      B_IPCHI2_OWNPV :
        normalized : true
        binning : [0, 20, 100]
        yscale  : 'log'
        labels  : ['$IP_{\chi^2}(B^+)$', '']
      B_FDCHI2_OWNPV :
        normalized : true
        binning : [0, 10000, 100]
        yscale  : 'log'
        labels  : ['$FD_{\chi^2}(B^+)$', '']
      B_ENDVERTEX_CHI2DOF:
        normalized : true
        binning : [0, 9, 100]
        yscale  : 'log'
        labels  : ['$\chi^2/dof(B^+)$', '']
      B_DIRA_OWNPV:
        normalized : true
        binning : [0.9995, 1, 100]
        yscale  : 'log'
        labels  : ['DIRA$(B^+)$', '']
      #
      Jpsi_PT :
        normalized : true
        binning : [0, 30000, 100]
        yscale  : 'log'
        labels  : ['$p_T(J/\psi)$', '']
      Jpsi_IPCHI2_OWNPV:
        normalized : true
        binning : [0, 500, 100]
        yscale  : 'log'
        labels  : ['$IP_{\chi^2}(J/\psi)$', '']
      Jpsi_CHI2DOF:
        normalized : true
        binning : [0, 10, 100]
        yscale  : 'log'
        labels  : ['$\chi^2/dof(J/\psi)$', '']
      Jpsi_DIRA_OWNPV:
        normalized : true
        binning : [0.99,  1, 100]
        yscale  : 'log'
        labels  : ['DIRA$(J/\psi)$', '']
        #
      min_ll_pt:
        normalized : true
        binning : [0, 10000, 100]
        yscale  : 'log'
        labels  : ['$\min(p_T(e^+), p_T(e^-))$', '']
      max_ll_pt:
        normalized : true
        binning : [0, 20000, 100]
        yscale  : 'log'
        labels  : ['$\max(p_T(e^+), p_T(e^-))$', '']
      min_ll_ipc:
        normalized : true
        binning : [0,  500, 100]
        yscale  : 'log'
        labels  : ['$\min(IP_{\chi^2}(e^+), IP_{\chi^2}(e^-))$', '']
      max_ll_ipc:
        normalized : true
        binning : [0, 3000, 100]
        yscale  : 'log'
        labels  : ['$\max(IP_{\chi^2}(e^+), IP_{\chi^2}(e^-))$', '']
        #
      H_PT :
        normalized : true
        binning : [0, 15000, 100]
        yscale  : 'log'
        labels  : ['$p_T(K^+)$', '']
      H_IPCHI2_OWNPV:
        normalized : true
        binning : [0, 2000, 100]
        yscale  : 'log'
        labels  : ['$IP_{\chi^2}(K^+)$', '']
        #
      mass:
        normalized : true
        binning : [4400, 6500, 50]
        yscale  : 'linear'
        labels  : ['$M(B^+)$', '']
      hop_mass:
        normalized : true
        binning : [1000, 7000, 60]
        yscale  : 'linear'
        labels  : ['$M_{HOP}(B^+)$', '']
      swp_cascade_mass_swp:
        normalized : true
        binning : [1700, 2200, 60]
        yscale  : 'linear'
        labels  : ['$M(K,\ell_{\to\pi})$', '']
      swp_jpsi_misid_mass_swp:
        normalized : true
        binning : [2800, 3400, 60]
        yscale  : 'linear'
        labels  : ['$M(K_{\to\ell},\ell)$', '']
